Repository KITSTABAdrienBaron/testMergeBot, pull requests merged in 2019-04, with the labels that each got.

#13 [1] ![1] change 1
  README.md
Labels: Ready to auto merge

#14 [1] change 1
  README.md
Labels: Merge me

#15 [1] change 2
  NEW_FILE.md
Labels: Merge me

#16 [1] ![1] conflict with 1
  README.md
Labels: Merge me

#18 [1] commit 1
  DEVELOP.md
Labels: Merge me

#17 [1] ![1] commit 1
  README.md
Labels: Merge me

#19 [1] commit 1
  README.md
Labels: Merge me

#20 [1] commit 2
  NEW_FILE.md
Labels: Merge me

#21 [1] commit 1
  README.md
Labels: Merge me

#23 [1] Feature/1
  DEVELOP.md
  NEW_FILE.md
  README.md
Labels: Merge me

#24 [1] ![1] Feature/2
  REBASE.md
Labels: Merge me

#27 [1] cleanup some files
  DEVELOP.md
  NEW_FILE.md
  REBASE.md
Labels: Merge me

#28 [1] Feature/lots of commits
  LOTS_COMMITS.md
  createCommits.sh
Labels: Merge me

#29 [1] Feature/lots commits 2
  LOTS_COMMITS_2.md
  createCommits2.sh
Labels: Merge me

#30 [1] theo-test
  src/sum.js
  src/sum.test.js
Labels: Merge me

#31 [1] Refactor theo-test
  src/add.js
  src/add.test.js
  src/minus.js
  src/minus.test.js
  src/sum.js
  src/sum.test.js
Labels: Merge me next

#38 [1] Adds conflicting code
  src/sum.js
  src/sum.test.js
Labels: Merge me or wait

#34 [1] C1
  c-tests/one
  c-tests/three
Labels: Merge me

#37 [1] C1 3
  c-tests/four
Labels: Merge me

#35 [1] C1 1
  c-tests/two
Labels: Merge me

#39 [1] ![WIP] Add adrien function
  src/adrien.js
Labels: Merge me

#25 [1] Update tests of sum function to include additional test case
  src/sum.test.js
Labels: Merge me next

#40 [1] delete lots commits files
  LOTS_COMMITS.md
  LOTS_COMMITS_2.md
Labels: Merge me

#46 [1] Feature/7
  FEATURE_4.md
  FEATURE_5.md
Labels: Merge me next

#45 [3] Feature/6
  FEATURE_5.md
Labels: Merge me

#47 [1] Add code styling to `README`
  README.md
Labels: Merge me

#32 [1] Feature/add subtract
  src/SBTRKT.js
  src/SBTRKT.test.js
  src/sum.test.js
Labels: Merge me or wait

#26 [1] Add more test of different sums
  src/sum.test.js
Labels: Merge me or wait

#48 [1] remove feature MDs
  FEATURE_4.md
  FEATURE_5.md
Labels: Merge me
